Chore/218 automatically build and install vrrclient
Oeffis/Oeffis pull request #219
Opened 2023-08-03 12:36 UTC by JaJako

### Description

For now a new script is added to install vrr_client to Backend manually.

## Checklist

- [ ] My code follows the style guidelines
- [ ] I have documented my code
- [ ] My changes generate no new warnings
- [ ] I have linked the Issue
- [ ] The Pull Request covers all the Checkpoints from the tagged Issue
- [ ] I have noted the hours of work i have put in the issue

## I have edited following Parts of the project

- [ ] Frontend
- [ ] Backend
- [ ] Github
- [ ] Root

## If tests are required did you make them?

- [ ] No tests required
- [ ] Yes
- [ ] No

2023-08-03 12:43 UTC, JaJako commented
@Oeffis/core-team I have added a new npm script to backend which builds @oeffis/vrr_client package locally and installs it to backend. What @timvahlbrock suggested (some kind of background task within a file watcher) I did´t get a concrete idea of how to implement that. Maybe someone else wants to look at this at time, too.

2023-08-10 14:41 UTC, JaJako commented
Found a way so that vrr_client is build when running backend both in vscode and Webstorm and (re)builds automatically when files in vrr_client are edited while running.

2023-08-11 12:37 UTC, JaJako commented
Building vrr_client in pipeline/checks is fixed now. Separated "default" build script (without watch) and the new build script that's watching for changed files. (Dunno if that's the best solution, but at least it's working fine in vscode and webstorm.)

2023-08-18 08:50 UTC, timvahlbrock requested changes

2023-08-18 08:50 UTC, timvahlbrock commented on README.md
> +2. Install NPM packages in Oeffis/vrr_client, Oeffis/backend and Oeffis/frontend (sticking to this order):
the "sticking to this order" info here is good, but I think we should also add the info, why this is necessary. Maybe this isn't the case anymore in the future and then we wouldn't know wether we can remove this notice.

2023-08-18 08:50 UTC, timvahlbrock commented on .vscode/tasks.json
>          {
This second problem match is not needed. `$tsc-watch` is the only problemMatcher you need, if all you do is run `tsc watch`, that's what its for.

2023-08-18 08:50 UTC, timvahlbrock commented on .vscode/tasks.json
>          {
Also: the second problem matcher will never have its endsPattern matched, because tsc does not print "Nest application successfully started"

2023-08-31 14:05 UTC, Paulomart approved these changes

2023-08-31 14:06 UTC, merged