Implement service to handle favorites
Oeffis/Oeffis pull request #253
Opened 2023-08-22 08:44 UTC by Paulomart

### Description

Closes #91

## Checklist

- [x] My code follows the style guidelines
- [x] I have documented my code
- [x] My changes generate no new warnings
- [x] I have linked the Issue
- [x] The Pull Request covers all the Checkpoints from the tagged Issue
- [x] I have noted the hours of work i have put in the issue

## I have edited following Parts of the project

- [x] Frontend
- [ ] Backend
- [ ] Github
- [ ] Root

## If tests are required did you make them?

- [ ] No tests required
- [x] Yes
- [ ] No

2023-08-22 13:34 UTC, Paulomart commented
@timvahlbrock this fails because an OEM error:

```
⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯
Error: Worker terminated due to reaching memory limit: JS heap out of memory
 ❯ new NodeError node:internal/errors:405:5
 ❯ [kOnExit] node:internal/worker:287:26
 ❯ Worker.<computed>.onexit node:internal/worker:209:20

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: {
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
  "code": "ERR_WORKER_OUT_OF_MEMORY",
}
```

I already increased the memory via `NODE_OPTIONS=--max-old-space-size=8192`, but this didnt seem to help.

2023-08-24 07:31 UTC, Paulomart commented
@timvahlbrock whooops that was my fault. Had a bad test...

2023-08-30 15:14 UTC, timvahlbrock commented
favourite is British English. Are we bothered by that?

2023-08-30 15:18 UTC, Paulomart commented
@Paulomart aghr ups. But I feel the change isn't worth the time...

2023-08-30 15:27 UTC, timvahlbrock requested changes

2023-08-30 15:27 UTC, timvahlbrock commented on frontend/src/services/persistence/generatePersistedObjectStorage.tsx
> +        console.log("addPersistedObject", createPersistedObject);
Debug statements in prod code

2023-08-30 15:33 UTC, Paulomart commented
> And another thing: Would we reduce much of the effort if we used https://github.com/ionic-team/ionic-storage ?

I would be possible but that would have effected #225. This builds on top of that.

2023-08-30 15:35 UTC, Paulomart commented on frontend/src/services/persistence/generatePersistedObjectStorage.tsx
> +        console.log("addPersistedObject", createPersistedObject);
Done

2023-08-30 19:01 UTC, Paulomart commented
/rebase

2023-08-31 14:08 UTC, Paulomart commented
/rebase

2023-08-31 14:46 UTC, merged