Add UI to remove and add favourite locations in search
Oeffis/Oeffis pull request #273
Opened 2023-08-30 12:51 UTC by Paulomart

https://github.com/Oeffis/Oeffis/assets/4148404/0ff54ea9-315c-4c0b-a9f0-315412f5bab6

### Description

Closes #272 

## Checklist

- [x] My code follows the style guidelines
- [x] I have documented my code
- [x] My changes generate no new warnings
- [x] I have linked the Issue
- [x] The Pull Request covers all the Checkpoints from the tagged Issue
- [x] I have noted the hours of work i have put in the issue

## I have edited following Parts of the project

- [x] Frontend
- [ ] Backend
- [ ] Github
- [ ] Root

## If tests are required did you make them?

- [ ] No tests required
- [ ] Yes
- [x] No

2023-09-01 12:00 UTC, timvahlbrock approved these changes
Nice work. Especially that you already included showing the favourites when no search query is put in.

2023-09-01 12:01 UTC, timvahlbrock requested changes

2023-09-01 12:01 UTC, timvahlbrock commented on .vscode/settings.json
> -  "git.mergeEditor": true,
sorry but this need to be fixed before.

2023-09-01 12:14 UTC, Paulomart commented
I think its better to merge #281 first and then come back to this pr.

2023-09-03 09:57 UTC, timvahlbrock requested changes

2023-09-03 09:57 UTC, timvahlbrock commented on frontend/src/components/LocationSearch/LocationIcon.tsx
> +  type: string;
we could get more precise by using `keyof ICON_MAP` here, but I don't know if react bindings are that precise

2023-09-03 11:12 UTC, timvahlbrock approved these changes

2023-09-03 11:29 UTC, merged