implement abstraction layer on top of leafletmapcontainer to listen t…
Oeffis/Oeffis pull request #409
Opened 2023-11-02 13:19 UTC by timvahlbrock

2023-11-02 13:22 UTC, timvahlbrock commented
@Paulomart the main issue I'm currently having is, that my useEffect function is called, before the html is first rendered. The width and height of the container will therefore be 0. The map will then only render a single tile, which makes it look like this:

<img width="436" alt="image" src="https://github.com/Oeffis/Oeffis/assets/25803754/31e71bbe-1a5d-4e51-ad0c-c1ed3f4d08c3">

Do you have an idea on how to delay the useEffect hook until after the first render?

2023-11-02 14:07 UTC, timvahlbrock commented
Issue with map shaking and reset persists, but is eliminated as soon as `useCurrentTime` hook is disabled.

2023-11-02 14:26 UTC, timvahlbrock commented
> @Paulomart the main issue I'm currently having is, that my useEffect function is called, before the html is first rendered. The width and height of the container will therefore be 0. The map will then only render a single tile, which makes it look like this:
> 
> <img alt="image" width="436" src="https://user-images.githubusercontent.com/25803754/280002039-31e71bbe-1a5d-4e51-ad0c-c1ed3f4d08c3.png">
> Do you have an idea on how to delay the useEffect hook until after the first render?

@Paulomart suggested to use `useLayoutEffect` instead of `setTimeout`, which reduces the likeliness of the problem occurring, but doesn't eliminate it.

2023-11-02 20:12 UTC, Paulomart requested changes

2023-11-02 20:12 UTC, Paulomart commented on frontend/src/components/map/LeafletMapContainer.tsx
> +  const renderMarker = (): ReactElement[] =>
no need to use a function for this. just use a const

2023-11-02 20:12 UTC, Paulomart commented on frontend/src/components/map/LeafletMapContainer.tsx
> +      : <></>}
```suggestion
    {showLines &&
      <Polygon color={"rgb(77, 77, 77)"} opacity={1} dashArray={"20,15"} weight={2} positions={getPolygonPositions()} />}
```

2023-11-02 20:12 UTC, Paulomart commented on frontend/src/components/map/LeafletMapContainer.tsx
> +    {<CurrentLocationMapMarker />}
```suggestion
    <CurrentLocationMapMarker />
```

2023-11-02 20:12 UTC, Paulomart commented on frontend/src/components/map/LeafletMapContainer.tsx
> +  const [view, setView] = useState<View>({ bounds: [[50.30527, 5.71687], [52.69499, 9.47241]] });
maybe extract these consts

2023-11-02 20:12 UTC, Paulomart commented on frontend/src/components/map/ReactiveMapContainer.tsx
> +};
if you are using ( then please format it nice :)

```suggestion
  return (
    <MapContainer
      style={props.style}
      ref={mapRef}
      maxZoom={15}
    >
      {props.children}
    </MapContainer>
  );
};
```

2023-11-03 08:48 UTC, Paulomart requested changes

2023-11-03 08:48 UTC, Paulomart commented on frontend/src/components/map/LeafletMapContainer.tsx
> +      : <></>}
```suggestion
    {showLines && <Polygon color={"rgb(77, 77, 77)"} opacity={1} dashArray={"20,15"} weight={2} positions={bounds} />}
```

Deja Vu?

![whoa-deja-vu-matrix-glitch](https://github.com/Oeffis/Oeffis/assets/4148404/6b8f7eaf-ea2c-4858-9c46-8aa9cb7adf50)

2023-11-03 08:51 UTC, Paulomart approved these changes

2023-11-03 09:00 UTC, merged